language: ruby

rvm:
  - 2.7.1

cache: bundler

branches:
  only:
    - master

env:
  global:
    - DEPLOY_BRANCH=gh-pages
    - JEKYLL_ENV=production

script: scripts/build.sh

deploy:
  provider: script
  skip_cleanup: true
  script: scripts/deploy.sh
  on:
    branch: master