# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: API Handyman
author: Arnaud Lauret
description: "Hi! I'm Arnaud Lauret, the API Handyman and author of The Design of Web APIs. I like to share what I do, struggle with, learn, and teach while working in the API space."
url: "https://apihandyman.io" # the base hostname & protocol for your site
baseurl: ""

sass:
  style: compressed # possible values: nested expanded compact compressed
  load_paths:
      - css
      - _sass

# Social links
twitter_username: apihandyman
github_username:  arno-di-loreto
linkedin_username: arnaudlauret

# Page default page banner
default_banner: /images/commons/default.png

# What's before this will be shown in post summary'
excerpt_separator: <!--more-->

# Pagination parameters
# jekyll-paginate-v2 
# https://github.com/sverrirs/jekyll-paginate-v2/blob/master/README-GENERATOR.md
pagination:
  enabled: true
  sort_reverse: true
  debug: false
  per_page: 10
  trail: 
    before: 1 # The number of links before the current page
    after: 1  # The number of links after the current page

# Third party parameters
google_analytics: UA-58046291-1

# Build settings
markdown: kramdown
kramdown:
  input: GFM
## code highlight
### disabling default code highlighter
highlighter: none
### codefilehighlight parameter: where code files are stored
coderoot: code
### codefilehighlight parameter: number of visible lines in code block
codeblocksize: 20
###
codeblock_hidden_copy_separator: ---COPY_CONTENT_SEPARATOR---

# Links
mybook: http://bit.ly/designwebapis
mybook_discount_code: fcclauret
mybook_discount_rate: 37% off

collections:
  tools:
    output: true
    sort_by: title

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate-v2 # https://github.com/sverrirs/jekyll-paginate-v2/blob/master/README-GENERATOR.md

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - scripts
  - .travis.yml
  - .gitignore
  # to avoid Invalid date '<%= Time.now.strftime('%Y-%m-%d %H:%M:%S %z') %>': Document 'vendor/cache/gems/jekyll-3.2.1/lib/site_template/_posts/0000-00-00-welcome-to-jekyll.markdown.erb' does not have a valid date in the YAML front matter.
  # See https://github.com/jekyll/jekyll/issues/5267  
  - vendor

debug: false