name: Jekyll site CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"
    - name: Download gh-pages
      run: |
        git clone --depth 1 https://{{secrets.GH_TOKEN}}@github.com/arno-di-loreto/apihandyman.io  --branch gh-pages-test --single-branch gh-pages-test
    - name: Cleaning gh-pages and copying from _site
        rm -rf gh-pages-test/*
        cp -r _site/* gh-pages-test
    - name: Commit updated gh-pages
        cd gh-pages-test
        git add .
        git commit -m "publish"
        git push
        
